server:
  port: 9000

spring:
  r2dbc:
    url: r2dbc:mysql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useLocalSessionState=true&useLocalTransactionState=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
        
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

collector:
  queue-name: ${QUEUE_NAME}
  bucket-name: ${BUCKET_NAME}
